const PRODUCTS = [
  {
    id: "kimono-dzen",
    name: "Кимоно Дзен",
    cardTitle: "Кимоно Дзен",
    category: "Одежда",
    price: 4444,
    image: "assets/images/kimono-main.png",
    images: ["assets/images/kimono-main.png", "assets/images/kimono-2.png"],
    description:
      "Свободная форма для движения, практики и спокойной повседневности.",
    material: "Хлопок, ручная вышивка",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопок, ручная вышивка" },
      { label: "крой", value: "свободный" },
      { label: "место производства", value: "ручная работа" },
    ],
    relatedIds: ["bokken-dzen", "kniga-prostranstvo", "vinil-ptitsy"],
  },
  {
    id: "bokken-dzen",
    name: "Боккен",
    cardTitle: "Боккен",
    category: "Другое",
    price: 2999,
    image: "assets/images/bokken.png",
    images: ["assets/images/bokken.png", "assets/images/bokken-2.png"],
    description: "Деревянный меч для тренировок в духе самурайской школы.",
    material: "Прочный дуб",
    sizes: [],
    specs: [
      { label: "состав", value: "дуб" },
      { label: "назначение", value: "тренировка формы" },
    ],
    relatedIds: ["kimono-dzen", "posters-school-dzen", "vinil-ptitsy"],
  },
  {
    id: "kniga-prostranstvo",
    name: "Книга «Пространство Дзен»",
    cardTitle: "Книга Дзен",
    category: "Печатное",
    price: 1499,
    image: "assets/images/mbook.png",
    images: [
      "assets/images/mbook.png",
      "assets/images/kniga-prostranstvo-2.png",
    ],
    description: "Печатное издание о форме, ритуале и внутренней концентрации.",
    material: "Бумага, твёрдый переплёт",
    sizes: [],
    specs: [
      { label: "формат", value: "твёрдый переплёт" },
      { label: "состав", value: "бумага, печать" },
    ],
    relatedIds: ["posters-school-dzen", "shopper-dzen", "vinil-ptitsy"],
  },
  {
    id: "vinil-ptitsy",
    name: "Пластинка «Клич перелётных птиц»",
    cardTitle: "Пластинка",
    category: "Другое",
    price: 999,
    image: "assets/images/musplast.png",
    images: ["assets/images/musplast.png"],
    description: "Звуковая среда для практики, паузы и движения.",
    material: "Винил",
    sizes: [],
    specs: [
      { label: "формат", value: "винил, LP" },
      { label: "состав", value: "винил" },
    ],
    relatedIds: ["bokken-dzen", "shopper-dzen", "kniga-prostranstvo"],
  },
  {
    id: "shopper-dzen",
    name: "Шоппер Дзен",
    cardTitle: "Шоппер",
    category: "Аксессуары",
    price: 1490,
    image: "assets/images/shopper-dzen-main.png",
    images: [
      "assets/images/shopper-dzen-main.png",
      "assets/images/shopper-dzen-worn.png",
    ],
    description: "Чёрный шоппер из плотного холста с клеткой и графикой DZEN в синей палитре.",
    material: "Хлопок, усиленные ручки",
    sizes: [],
    specs: [
      { label: "состав", value: "хлопок, усиленные ручки" },
      { label: "дизайн", value: "шахматная сетка, принт DZEN" },
      { label: "назначение", value: "повседневное ношение" },
    ],
    relatedIds: ["kimono-dzen", "kniga-prostranstvo", "vinil-ptitsy"],
  },
  {
    id: "bag-dzen",
    name: "Сумка Дзен",
    cardTitle: "Сумка",
    category: "Аксессуары",
    price: 3290,
    image: "assets/images/bag-dzen-main.png",
    images: [
      "assets/images/bag-dzen-main.png",
      "assets/images/bag-dzen-worn.png",
    ],
    description:
      "Большая сумка через плечо из плотной ткани с утяжкой посередине и вышивкой иероглифа «дзен».",
    material: "Хлопок, полиэстер",
    sizes: [],
    specs: [
      { label: "состав", value: "хлопок с напылением синтетики, шнуры" },
      { label: "тип", value: "мешок на плечевом ремне с шнурком" },
      { label: "детали", value: "вышивка 禅 у нижней кромки" },
    ],
    relatedIds: ["shopper-dzen", "belt-dzen", "panama-dzen"],
  },
  {
    id: "backpack-atelier-dzen",
    name: "Рюкзак «Atelier Дзен»",
    cardTitle: "Рюкзак Atelier",
    category: "Аксессуары",
    price: 3990,
    image: "assets/images/backpack-atelier-main.png",
    images: [
      "assets/images/backpack-atelier-main.png",
      "assets/images/backpack-atelier-worn.png",
    ],
    description:
      "Компактный рюкзак-слинг тёмно-синего тона с жаккардовой графикой, кандзи 禅 и шевроном «THROUGH CHAOS FIND BALANCE».",
    material: "Хлопок, нейлон",
    sizes: [],
    specs: [
      { label: "состав", value: "хлопок, нейлоновые ремни" },
      { label: "тип", value: "слинг с верхней ручкой и плечевым ремнём" },
      { label: "детали", value: "жаккард, чёрная фурнитура, шеврон 禅" },
    ],
    relatedIds: ["hoodie-atelier-dzen", "bag-dzen", "shopper-dzen"],
  },
  {
    id: "crossbody-madfrenzy-dzen",
    name: "Кросс-боди «MadFrenzy Дзен»",
    cardTitle: "Кросс-боди MadFrenzy",
    category: "Аксессуары",
    price: 2990,
    image: "assets/images/crossbody-madfrenzy-worn.png",
    images: [
      "assets/images/crossbody-madfrenzy-worn.png",
      "assets/images/crossbody-madfrenzy-main.png",
    ],
    description:
      "Компактная сумка через плечо тёмно-синего тона с жаккардовой графикой, карабинами и патчами «MADFRENZY» и «THROUGH CHAOS FIND BALANCE».",
    material: "Хлопок, нейлон",
    sizes: [],
    specs: [
      { label: "состав", value: "хлопок, нейлоновые ремни" },
      { label: "тип", value: "сумка через плечо с верхней ручкой" },
      { label: "детали", value: "жаккард, карабины, патчи 禅 и MADFRENZY" },
    ],
    relatedIds: ["backpack-atelier-dzen", "bag-dzen", "shopper-dzen"],
  },
  {
    id: "sunglasses-beyond-chaos-dzen",
    name: "Очки «Beyond Chaos Дзен»",
    cardTitle: "Очки Beyond Chaos",
    category: "Аксессуары",
    price: 2490,
    image: "assets/images/sunglasses-beyond-chaos-main.png",
    images: [
      "assets/images/sunglasses-beyond-chaos-main.png",
      "assets/images/sunglasses-beyond-chaos-worn.png",
    ],
    description:
      "Спортивные солнцезащитные очки в матовой синей оправе с зеркальными линзами и гравировкой BEYOND CHAOS на дужке.",
    material: "Пластик, поликарбонат",
    sizes: [],
    specs: [
      { label: "оправа", value: "матовый пластик, синий" },
      { label: "линзы", value: "зеркальные, серебро" },
      { label: "стиль", value: "sport-wrap, гравировка BEYOND CHAOS" },
    ],
    relatedIds: ["crossbody-madfrenzy-dzen", "backpack-atelier-dzen", "cap-blue-moon-dzen"],
  },
  {
    id: "tee-samurai-dzen",
    name: "Футболка Самурай Дзен",
    cardTitle: "Футболка Самурай",
    category: "Одежда",
    price: 2590,
    image: "assets/images/tee-samurai-back.png",
    images: [
      "assets/images/tee-samurai-back.png",
      "assets/images/tee-samurai-front.png",
    ],
    description: "Оверсайз футболка с графикой самурая и акцентной синей типографикой.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "100% хлопок" },
      { label: "крой", value: "oversize" },
      { label: "принт", value: "шелкография" },
    ],
    relatedIds: ["kimono-dzen", "shopper-dzen", "bokken-dzen"],
  },
  {
    id: "pendant-dzen",
    name: "Подвеска Дзен",
    cardTitle: "Подвеска",
    category: "Аксессуары",
    price: 1890,
    image: "assets/images/pendant-dzen-main.png",
    images: [
      "assets/images/pendant-dzen-main.png",
      "assets/images/pendant-dzen-worn.png",
    ],
    description: "Металлическая подвеска с символом Дзен для повседневного образа.",
    material: "Нержавеющая сталь",
    sizes: [],
    specs: [
      { label: "состав", value: "нержавеющая сталь" },
      { label: "тип", value: "подвеска на цепочке" },
      { label: "покрытие", value: "полированная сталь" },
    ],
    relatedIds: ["shopper-dzen", "tee-samurai-dzen", "kimono-dzen"],
  },
  {
    id: "ring-dzen",
    name: "Перстень Дзен",
    cardTitle: "Перстень",
    category: "Аксессуары",
    price: 2290,
    image: "assets/images/ring-dzen-main.png",
    images: [
      "assets/images/ring-dzen-main.png",
      "assets/images/ring-dzen-worn.png",
    ],
    description: "Серебристый перстень с геометрическим знаком на круглой шинке и матовой фактурой.",
    material: "Сплав с оксидированием",
    sizes: [],
    specs: [
      { label: "состав", value: "сплав, оксидирование" },
      { label: "тип", value: "перстень-печатка" },
      { label: "фактура", value: "матовая, антик" },
    ],
    relatedIds: ["pendant-dzen", "belt-dzen", "shopper-dzen"],
  },
  {
    id: "ring-menpo-dzen",
    name: "Перстень Самурай",
    cardTitle: "Перстень Самурай",
    category: "Аксессуары",
    price: 3790,
    image: "assets/images/ring-menpo-main.png",
    images: [
      "assets/images/ring-menpo-main.png",
      "assets/images/ring-menpo-worn.png",
    ],
    description: "Массивный перстень с рельефом маски самурая, детализированным шлемом и мотивом пагоды.",
    material: "Сплав под серебро, оксидирование",
    sizes: [],
    specs: [
      { label: "состав", value: "сплав, античное патинирование" },
      { label: "декор", value: "рельеф менпо, иероглифы «бусидо»" },
      { label: "стиль", value: "фурнитурный акцент под японский мотив" },
    ],
    relatedIds: ["ring-dzen", "bokken-dzen", "kimono-dzen"],
  },
  {
    id: "bracelet-samurai-dzen",
    name: "Браслет «Самурай Дзен»",
    cardTitle: "Браслет Самурай",
    category: "Аксессуары",
    price: 3490,
    image: "assets/images/bracelet-samurai-main.png",
    images: [
      "assets/images/bracelet-samurai-main.png",
      "assets/images/bracelet-samurai-worn.png",
    ],
    description:
      "Массивный браслет с медальоном-менпо в центре, панелями с пагодой и горой Фудзи; состаренное серебро и матовая фактура.",
    material: "Сплав под серебро, оксидирование",
    sizes: [],
    specs: [
      { label: "состав", value: "сплав, античное оксидирование" },
      { label: "декор", value: "маска менпо, пагода, гора Фудзи" },
      { label: "стиль", value: "массивный, восточный мотив" },
    ],
    relatedIds: ["ring-menpo-dzen", "ring-dzen", "pendant-dzen"],
  },
  {
    id: "belt-dzen",
    name: "Ремень Дзен",
    cardTitle: "Ремень",
    category: "Аксессуары",
    price: 2190,
    image: "assets/images/belt-dzen-main.png",
    images: [
      "assets/images/belt-dzen-main.png",
      "assets/images/belt-dzen-worn.png",
    ],
    description: "Текстильный ремень с металлической пряжкой и минимальной графикой Дзен.",
    material: "Нейлон, металл",
    sizes: [],
    specs: [
      { label: "состав", value: "нейлон, металл" },
      { label: "тип", value: "ремень с фиксирующей пряжкой" },
      { label: "покрытие", value: "матовый черный металл" },
    ],
    relatedIds: ["pendant-dzen", "tee-samurai-dzen", "shopper-dzen"],
  },
  {
    id: "tee-night-dzen",
    name: "Футболка Ночной Зен",
    cardTitle: "Футболка Ночной Зен",
    category: "Одежда",
    price: 2490,
    image: "assets/images/tee-night-main.png",
    images: [
      "assets/images/tee-night-main.png",
      "assets/images/tee-night-worn.png",
    ],
    description: "Оверсайз футболка с тёмным графическим принтом в настроении ночного ритуала.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "100% хлопок" },
      { label: "крой", value: "oversize" },
      { label: "принт", value: "полноформатная шелкография" },
    ],
    relatedIds: ["tee-samurai-dzen", "belt-dzen", "pendant-dzen"],
  },
  {
    id: "panama-dzen",
    name: "Панамка Дзен",
    cardTitle: "Панамка",
    category: "Аксессуары",
    price: 1990,
    image: "assets/images/panama-dzen-main.png",
    images: [
      "assets/images/panama-dzen-main.png",
      "assets/images/panama-dzen-worn.png",
    ],
    description: "Панамка с тёмным графическим паттерном для города и практики на открытом воздухе.",
    material: "Полиэстер",
    sizes: [],
    specs: [
      { label: "состав", value: "полиэстер" },
      { label: "тип", value: "панама с утяжкой" },
      { label: "особенность", value: "вентиляционные люверсы" },
    ],
    relatedIds: ["belt-dzen", "tee-night-dzen", "pendant-dzen"],
  },
  {
    id: "hoodie-dzen",
    name: "Худи Дзен",
    cardTitle: "Худи Дзен",
    category: "Одежда",
    price: 4290,
    image: "assets/images/hoodie-dzen-main.png",
    images: [
      "assets/images/hoodie-dzen-main.png",
      "assets/images/hoodie-dzen-worn.png",
    ],
    description: "Оверсайз худи с эффектом состаренного денима и минимальным знаком «дзен» на груди.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопок с эффектом stonewash" },
      { label: "крой", value: "oversize, капюшон" },
      { label: "особенность", value: "нижняя завязка по талии" },
    ],
    relatedIds: ["kimono-dzen", "tee-night-dzen", "panama-dzen"],
  },
  {
    id: "hoodie-atelier-dzen",
    name: "Худи «Atelier Дзен»",
    cardTitle: "Худи Atelier",
    category: "Одежда",
    price: 4690,
    image: "assets/images/hoodie-atelier-main.png",
    images: [
      "assets/images/hoodie-atelier-main.png",
      "assets/images/hoodie-atelier-worn.png",
    ],
    description:
      "Чёрный оверсайз худи с индиго-жаккардом и вышивкой: иероглиф 四禅, лотосы на рукавах и логотип DZEN MENSWEAR STUDIO & ATELIER.",
    material: "Хлопок, акрил",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопок, акрил" },
      { label: "крой", value: "oversize, капюшон со шнурами" },
      { label: "отделка", value: "жаккардовое плетение и вышивка индиго" },
    ],
    relatedIds: ["hoodie-dzen", "sweatshirt-samurai-dzen", "sweater-samurai-dzen"],
  },
  {
    id: "sweatshirt-dzen",
    name: "Свитшот Дзен",
    cardTitle: "Свитшот Дзен",
    category: "Одежда",
    price: 3890,
    image: "assets/images/sweatshirt-dzen-main.png",
    images: [
      "assets/images/sweatshirt-dzen-main.png",
      "assets/images/sweatshirt-dzen-worn.png",
    ],
    description: "Оверсайз свитшот с круглым вырезом и состаренным кислотным эффектом ткани.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопок, футер с эффектом acid wash" },
      { label: "крой", value: "oversize, округлая горловина" },
      { label: "отделка", value: "микс-под резинку на манжетах и низу" },
    ],
    relatedIds: ["hoodie-dzen", "kimono-dzen", "tee-samurai-dzen"],
  },
  {
    id: "sweatshirt-elements-dzen",
    name: "Свитшот «Стихии»",
    cardTitle: "Свитшот Стихии",
    category: "Одежда",
    price: 4190,
    image: "assets/images/sweatshirt-elements-worn.png",
    images: [
      "assets/images/sweatshirt-elements-worn.png",
      "assets/images/sweatshirt-elements-main.png",
    ],
    description:
      "Чёрный оверсайз свитшот с принтом из четырёх стихий: огня, воздуха, земли и воды.",
    material: "Хлопок, акрил",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопок, акрил" },
      { label: "крой", value: "oversize, круглая горловина" },
      { label: "принт", value: "квадрат из четырёх стихий" },
    ],
    relatedIds: ["sweatshirt-dzen", "hoodie-dzen", "tee-samurai-dzen"],
  },
  {
    id: "sweatshirt-samurai-dzen",
    name: "Свитшот «Самурай Дзен»",
    cardTitle: "Свитшот Самурай",
    category: "Одежда",
    price: 4290,
    image: "assets/images/sweatshirt-samurai-main.png",
    images: [
      "assets/images/sweatshirt-samurai-main.png",
      "assets/images/sweatshirt-samurai-worn.png",
    ],
    description:
      "Чёрный оверсайз свитшот с графической композицией — самурай, лотосы, иероглиф 四禅 и логотип DZEN.",
    material: "Хлопок, акрил",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопок, акрил" },
      { label: "крой", value: "oversize, круглая горловина" },
      { label: "принт", value: "графика «самурай и лотос»" },
    ],
    relatedIds: ["sweatshirt-elements-dzen", "sweater-samurai-dzen", "tee-samurai-dzen"],
  },
  {
    id: "sweater-samurai-dzen",
    name: "Свитер «Самурай Дзен»",
    cardTitle: "Свитер Самурай",
    category: "Одежда",
    price: 5490,
    image: "assets/images/sweater-samurai-main.png",
    images: [
      "assets/images/sweater-samurai-main.png",
      "assets/images/sweater-samurai-worn.png",
    ],
    description:
      "Оверсайз-свитер тёмно-серого тона с жаккардовой графикой марша самураев и логотипом DZEN по нижней кромке.",
    material: "Шерсть, акрил",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "шерсть, акрил" },
      { label: "крой", value: "oversize, круглая горловина" },
      { label: "принт", value: "жаккардовое плетение" },
    ],
    relatedIds: ["hoodie-dzen", "sweatshirt-dzen", "tee-samurai-dzen"],
  },
  {
    id: "tee-focus-dzen",
    name: "Футболка Focus Дзен",
    cardTitle: "Футболка Focus",
    category: "Одежда",
    price: 2390,
    image: "assets/images/tee-focus-dzen-main.png",
    images: [
      "assets/images/tee-focus-dzen-main.png",
      "assets/images/tee-focus-dzen-worn.png",
    ],
    description: "Чёрная оверсайз футболка с вертикальной мини-графикой DZEN: focus, discipline, victory.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "100% хлопок" },
      { label: "крой", value: "oversize, укороченный рукав" },
      { label: "принт", value: "шелкография на груди" },
    ],
    relatedIds: ["pendant-dzen", "belt-dzen", "tee-night-dzen"],
  },
  {
    id: "hoodie-wash-dzen",
    name: "Худи Wash Дзен",
    cardTitle: "Худи Wash",
    category: "Одежда",
    price: 4490,
    image: "assets/images/hoodie-wash-dzen-main.png",
    images: [
      "assets/images/hoodie-wash-dzen-main.png",
      "assets/images/hoodie-wash-dzen-worn.png",
    ],
    description: "Тёплое худи цвета винтаж-коричневого с эффектом acid wash и капюшоном на шнурах.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопок с эффектом mineral wash" },
      { label: "крой", value: "oversize, капюшон на завязках" },
      { label: "особенность", value: "карман «кенгуру» и диагональные швы" },
    ],
    relatedIds: ["hoodie-dzen", "sweatshirt-dzen", "tee-focus-dzen"],
  },
  {
    id: "tee-blocks-dzen",
    name: "Футболка Structure Дзен",
    cardTitle: "Футболка Structure",
    category: "Одежда",
    price: 2690,
    image: "assets/images/tee-dzen-blocks-main.png",
    images: [
      "assets/images/tee-dzen-blocks-main.png",
      "assets/images/tee-dzen-blocks-worn.png",
    ],
    description:
      "Выцветшая чёрная оверсайз футболка с крупной синей архитектурой и логотипом DZEN.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "100% хлопок" },
      { label: "эффект", value: "stonewash чёрный деним" },
      { label: "принт", value: "полноформатная графика, красный блок DZEN внизу" },
    ],
    relatedIds: ["tee-samurai-dzen", "tee-night-dzen", "belt-dzen"],
  },
  {
    id: "tee-fuji-dzen",
    name: "Футболка Fuji Дзен",
    cardTitle: "Футболка Fuji",
    category: "Одежда",
    price: 2490,
    image: "assets/images/tee-fuji-main.png",
    images: ["assets/images/tee-fuji-main.png", "assets/images/tee-fuji-worn.png"],
    description:
      "Белая оверсайз футболка с пейзажем и сакурой, текст ZEN и короткой фразой про тишину.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "100% хлопок" },
      { label: "крой", value: "oversize, округлая горловина" },
      { label: "принт", value: "прямоугольный принт с видами Фудзи" },
    ],
    relatedIds: ["kimono-dzen", "posters-school-dzen", "tee-focus-dzen"],
  },
  {
    id: "hoodie-blue-moon-dzen",
    name: "Худи Blue Moon Дзен",
    cardTitle: "Худи Blue Moon",
    category: "Одежда",
    price: 4990,
    image: "assets/images/hoodie-blue-moon-main.png",
    images: [
      "assets/images/hoodie-blue-moon-main.png",
      "assets/images/hoodie-blue-moon-worn.png",
    ],
    description:
      "Чёрное oversize худи на молнии с контрастным синим кругом и утилитарными карманами на рукавах.",
    material: "Хлопок",
    sizes: ["S", "M", "L", "XL"],
    specs: [
      { label: "состав", value: "хлопковый футер" },
      { label: "крой", value: "oversize, асимметричная молния" },
      { label: "детали", value: "капюшон, шнуры, карманы на рукавах" },
    ],
    relatedIds: ["hoodie-dzen", "hoodie-wash-dzen", "tee-blocks-dzen"],
  },
  {
    id: "cap-blue-moon-dzen",
    name: "Кепка Blue Moon Дзен",
    cardTitle: "Кепка Blue Moon",
    category: "Аксессуары",
    price: 1690,
    image: "assets/images/cap-blue-moon-main.png",
    images: [
      "assets/images/cap-blue-moon-main.png",
      "assets/images/cap-blue-moon-worn.png",
    ],
    description:
      "Чёрная бейсболка с широким козырьком и крупным синим кругом, в одной графической линии с худи Blue Moon.",
    material: "Хлопок",
    sizes: [],
    specs: [
      { label: "состав", value: "100% хлопок" },
      { label: "крой", value: "классическая шестипанельная" },
      { label: "застёжка", value: "регулируемая, металлическая" },
    ],
    relatedIds: ["hoodie-blue-moon-dzen", "panama-dzen", "belt-dzen"],
  },
  {
    id: "posters-school-dzen",
    name: "Набор постеров «Школа новых самураев»",
    cardTitle: "Набор постеров",
    category: "Печатное",
    price: 2490,
    image: "assets/images/posters-set-1.png",
    images: [
      "assets/images/posters-set-1.png",
      "assets/images/posters-set-2.png",
    ],
    description:
      "Серия плакатов «Дзен — Школа новых самураев» в трёх настроениях. Один комплект — три листа.",
    material: "Плотная матовая бумага, офсетная печать",
    sizes: [],
    variants: [
      {
        id: "сет 1",
        label: "сет 1",
        image: "assets/images/posters-set-1.png",
      },
      {
        id: "сет 2",
        label: "сет 2",
        image: "assets/images/posters-set-2.png",
      },
      {
        id: "сет 3",
        label: "сет 3",
        image: "assets/images/posters-set-3.png",
      },
    ],
    specs: [
      { label: "состав", value: "плотная бумага, офсет" },
      { label: "формат", value: "3 листа в комплекте" },
      { label: "сюжет", value: "три набора, выбор на странице товара" },
    ],
    relatedIds: ["stickers-school-dzen", "kniga-prostranstvo", "kimono-dzen"],
  },
  {
    id: "stickers-school-dzen",
    name: "Набор стикеров «Дзен»",
    cardTitle: "Набор стикеров",
    category: "Печатное",
    price: 690,
    image: "assets/images/stickers-set-1.png",
    images: [
      "assets/images/stickers-set-1.png",
      "assets/images/stickers-set-2.png",
    ],
    description:
      "Виниловые стикеры в двух настроениях: чёрно-белая графика «Школа новых самураев» и яркий типографический сет.",
    material: "Виниловая плёнка, матовая",
    sizes: [],
    variants: [
      {
        id: "сет 1",
        label: "сет 1",
        image: "assets/images/stickers-set-1.png",
      },
      {
        id: "сет 2",
        label: "сет 2",
        image: "assets/images/stickers-set-2.png",
      },
    ],
    specs: [
      { label: "состав", value: "винил, матовая ламинация" },
      { label: "формат", value: "набор фигурных стикеров" },
      { label: "сюжет", value: "два набора, выбор на странице товара" },
    ],
    relatedIds: ["posters-school-dzen", "kniga-prostranstvo", "kimono-dzen"],
  },
];

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id);
}

function formatPrice(value) {
  return `${Number(value).toLocaleString("ru-RU")} ₽`;
}
